---
# handlers file for nextcloud
- name: Relabel nextcloud
  command: "restorecon -R {{ nextcloud_folder }}"
  listen: relabel_nextcloud

- name: Recreate selinux module nextcloud
  command: checkmodule -M -m -o /var/local/selinux-modules/nextcloud.mod /var/local/selinux-modules/nextcloud.te
  listen: selinux_module_nextcloud

- name: Package selinux module
  command: semodule_package -o /var/local/selinux-modules/nextcloud.pp -m /var/local/selinux-modules/nextcloud.mod
  listen: selinux_module_nextcloud

- name: Install selinux module
  command: semodule -i /var/local/selinux-modules/nextcloud.pp
  listen: selinux_module_nextcloud

- name: Restart fail2ban
  service:
    name: fail2ban
    state: restarted
  listen: selinux_module_nextcloud

- name: Restart coolwsd
  service:
    name: coolwsd
    state: restarted
  listen: restart_coolwsd

- name: Restart notify_push
  service:
    name: notify_push
    state: restarted
  listen: restart_notify_push
