- name: Import facts
  import_tasks: "../../default_facts/default_facts.yml"

- name: "Install minidlna"
  dnf:
    name: minidlna
    state: latest

- name: "Unset media dir"
  lineinfile:
    path: "/etc/minidlna.conf"
    regexp: ".*media_dir=/.*"
    line: "#media_dir="

- name: "Unset media dirs"
  lineinfile:
    path: "/etc/minidlna.conf"
    insertafter: ".*media_dir="
    line: "media_dir={{ item.type }},/data/{{ item.dir }}"
  with_items:
   - { type: "A", dir: "music" }
   - { type: "V", dir: "videos" }

- name: "Set root container"
  lineinfile:
    path: "/etc/minidlna.conf"
    regexp: "#?root_container=.*"
    line: "root_container=B"
    state: present

- name: "Create .directory files"
  copy:
    dest: "{{ item.path }}/.directory"
    content: |
        [Desktop Entry]
        Icon={{ item.icon }}
  loop:
    - { path: "{{ music_folder }}", icon: folder-music }
    - { path: "{{ videos_folder }}", icon: folder-video }

- name: "Start services"
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - firewalld
    - minidlna

- name: "Enable minidlna in firewall"
  firewalld:
    service: minidlna
    permanent: true
    state: enabled
    immediate: true
