---
# tasks file for cockpit
- name: Import facts
  import_tasks: "../../default_facts/default_facts.yml"

- name: Install packages
  package:
    name:
      - cockpit
      - cockpit-networkmanager
      - cockpit-packagekit
      - cockpit-selinux
      - cockpit-storaged
      - cockpit-system
      - cockpit-ws
      - python3-urllib-gssapi
    state: present

- name: Get SSL certificate
  command:
    cmd: "ipa-getcert request -k {{ ssl_key }} -f {{ ssl_cert }} --wait"
    creates: "{{ ssl_cert }}"

- name: Create folder /etc/httpd
  file:
    path: /etc/httpd
    state: directory

- name: "Create service HTTP/{{ ansible_fqdn }}"
  ipaservice:
    name: "HTTP/{{ ansible_fqdn }}"
  environment: "{{ env_ipa_on_host }}"

- name: "Get keytab {{ httpd_keytab }}"
  shell:
    cmd: |
      kinit -k || exit 1
      ipa-getkeytab -p HTTP/{{ ansible_fqdn }} -k {{ httpd_keytab }} || exit 1
      kdestroy
    creates: "{{ httpd_keytab }}"
  environment: "{{ env_ipa_on_host }}"

- name: "Symlink keytab {{ httpd_keytab }} -> /etc/cockpit/krb5.keytab"
  file:
    state: link
    dest: /etc/cockpit/krb5.keytab
    src: "{{ httpd_keytab }}"

- name: "Start cockpit"
  service:
    name: cockpit.socket
    enabled: yes
    state: started

- name: "Open cockpit firewalld"
  firewalld:
    service: cockpit
    permanent: yes
    state: enabled
    immediate: yes
