---

# handlers file for evolution
- name: "Get users' home folders"
  shell:
    cmd: >-
      getent passwd --service=sss $( last | awk '/:0/ { print $1; }' | sort -u ) | awk -F: '($3 >= 1000) { print $6; }'
  register: get_active_users    
  listen: recreate_create_nextcloud_folders

- name: "Recreate /etc/skel/.bashrc.d/create-nextcloud-folders.sh"
  copy:
    src: /etc/skel/.bashrc.d/create-nextcloud-folders.sh
    dest: "{{ item }}/.bashrc.d/"
    remote_src: true
  with_items: "{{ get_active_users.stdout_lines }}" 
  listen: recreate_create_nextcloud_folders
