# tasks file for evolution
- name: Import facts
  import_tasks: "../../default_facts/default_facts.yml"

- name: Install evolution
  dnf:
    name:
        - evolution
        - openldap-clients
    state: latest

- name: Create folder /usr/local/etc/evolution
  file:
    path: /usr/local/etc/evolution
    state: directory


# 60c87fe7ff8c90d4d6652444232a129456024eeb.source
# -> autoconf.source
#
# b9367db2659447258a47f4835d7cab46b2370279.source
# -> autoconf-identity.source
#
# cc0693111afec299b324badfc0f1fa2d1803632d.source
# -> autoconf-transport.source
#
- name: copy evolution sources
  template:
    src: "{{ item }}"
    dest: /usr/local/etc/evolution
  with_items:
    - autoconf-identity.source
    - autoconf-transport.source
    - autoconf-imap.source
    - local.source
    - system-calendar.source

- name: "Copy Evolution Calendar Sources"
  template:
    src: autoconf-caldav-nextcloud.source
    dest: "/usr/local/etc/evolution/autoconf-caldav-nextcloud-{{ item.folder }}.source"
  with_items:
    - name: Personal
      folder: personal
      type: calendar
      color: "#55aaff"
    - name: Tasks
      folder: tasks
      type: tasks
      color: "#f0e2ef"
    - name: Birthdays
      folder: contact_birthdays
      type: calendar
      color: "#aaff7f"

- name: "Copy Evolution Addressbook Sources"
  template:
    src: autoconf-carddav-nextcloud.source
    dest: "/usr/local/etc/evolution/autoconf-carddav-nextcloud-{{ item.folder | replace(' ', '_') }}.source"
  with_items:
    - name: Accounts
      folder: z-server-generated--system
    - name: Personal
      folder: contacts
    - name: Recently contacted
      folder: z-app-generated--contactsinteraction--recent

- name: Install create-nextcloud-folders.sh
  template:
    src: create-nextcloud-folders.sh
    dest: /etc/skel/.bashrc.d

- name: Install evolution-autoconf.sh
  copy:
    src: evolution-autoconf.sh
    dest: /usr/local/bin
    mode: '0775'

- name: Install evolution-autoconf.desktop
  copy:
    src: evolution-autoconf.desktop
    dest: /etc/xdg/autostart
