- block:
    - name: "Add repo {{ arachnecdl_repo_url }}"
      yum_repository:
        name: "Arachne"
        baseurl: "{{ arachnecdl_repo_url }}"
      when: arachnecdl_repo_url != ""

    - name: "Add arachne copr repo {{ arachnecdl_copr_repo }}"
      copr:
        name: "{{ arachnecdl_copr_repo }}"
        chroot: "{{ (ansible_distribution == 'Fedora') | ternary(omit, 'epel-' + ansible_distribution_major_version + '-x86_64') }}"
      when: arachnecdl_copr_repo != ""
  when: foreman['organization'] is not defined

- name: "Install package"
  dnf:
    name: ArachneConfigDownloader
    state: latest

- name: "Set arachne server {{ arachnecdl_server_url }}"
  ini_file:
    path: "/etc/xdg/Claas Nieslony/Arachne Config Downloader.conf"
    section: General
    option: adminServerurl
    value: "{{ arachnecdl_server_url }}"
