# tasks file for zzz-finished

- name: "Find /etc/issue.d/please-wait.issue"
  stat:
    path: /etc/issue.d/please-wait.issue
  register: stat_please_wait

- name: "Does /etc/issue.d/please-wait.issue exist?"
  debug:
    msg: If yes, show message when finished
  changed_when: stat_please_wait.stat.exists
  notify: show_success_message
