# handlers file for webserver
- name: Restart httpd
  service:
    name: httpd
    state: restarted
  listen: restart_httpd

- name: Restart sssd
  service:
    name: sssd
    state: restarted
  listen: restart_sssd
