---
# tasks file for hostapd
- name: "Install kernel-ml"
  dnf:
    state: present
    name:
      - kernel-ml
      - kernel-ml-modules-extra
  register: install_kernel

- block:
  - name: "Reboot"
    reboot:

  - name: "Gather facts again"
    setup:
  when: install_kernel.changed

- name: "Find wifi adapter"
  set_fact:
    wifi_adapter: '{{ item }}'
  loop: "{{ ansible_facts.interfaces }}"
  when: item.startswith("wl")

- name: "Fail if no wifi adapter found"
  fail:
    msg: "No wifi adapter found"
  when: wifi_adapter is undefined or wifi_adapter == ""

- name: "Add NetworkManager plugin"
  ini_file:
    path: /etc/NetworkManager/NetworkManager.conf
    section: main
    option: plugins
    value: keyfile
  notify: restart_networkmanager

- name: "Ignore wifi interfaces by NetworkManager"
  copy:
    dest: /etc/NetworkManager/conf.d/99-unmanaged-devices.conf
    content: |
        [keyfile]
        unmanaged-devices=interface-name:wl*
  notify: restart_networkmanager

- name: "Configure bridge {{ bridge_name }}"
  nmcli:
    type: bridge
    conn_name: "{{ bridge_name }}"
    ifname: "{{ bridge_name }}"
    state: present
    autoconnect: yes
    stp: no
  notify: restart_networkmanager

- name: "Add NIC {{ bridge_slave_if }} to bridge"
  nmcli:
    type: bridge-slave
    conn_name: "{{ bridge_name }}-{{ bridge_slave_if }}"
    ifname: "{{ bridge_slave_if }}"
    state: present
    master: "{{ bridge_name }}"
    autoconnect: yes
  when: bridge_slave_if.startswith("eth") or bridge_slave_if.startswith("en")
  notify: restart_networkmanager

- name: "Flush handlers"
  meta: flush_handlers

- name: "Enable bridge"
  command: "nmcli con up {{ bridge_name }}-{{ bridge_slave_if }}"
  changed_when: no

- name: "Install packages"
  dnf:
    state: present
    name:
      - hostapd
      - iw
      - show-hotspot-settings
      - wireless-regdb

- name: "Install hostapd.conf"
  template:
    src: hostapd.conf
    dest: /etc/hostapd/hostapd.conf
  notify: restart_hostapd

- name: "Start services"
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - hostapd
    - httpd
