# handlers file for nextcloud
- name: Relabel nextcloud
  command: "restorecon -R {{ nextcloud_folder }}"
  listen: relabel_nextcloud

- name: Recreate selinux module postfix-extra
  command: checkmodule -M -m -o /var/local/selinux-modules/postfix-extra.mod /var/local/selinux-modules/postfix-extra.te
  listen: selinux_module_postfix_extra

- name: Package selinux module
  command: semodule_package -o /var/local/selinux-modules/postfix-extra.pp -m /var/local/selinux-modules/postfix-extra.mod
  listen: selinux_module_postfix_extra

- name: Install selinux module
  command: semodule -i /var/local/selinux-modules/postfix-extra.pp
  listen: selinux_module_postfix_extra

- name: Recreate selinux module nextcloud
  command: checkmodule -M -m -o /var/local/selinux-modules/nextcloud.mod /var/local/selinux-modules/nextcloud.te
  listen: selinux_module_nextcloud

- name: Package selinux module
  command: semodule_package -o /var/local/selinux-modules/nextcloud.pp -m /var/local/selinux-modules/nextcloud.mod
  listen: selinux_module_nextcloud

- name: Install selinux module
  command: semodule -i /var/local/selinux-modules/nextcloud.pp
  listen: selinux_module_nextcloud

- name: Restart fail2ban
  service:
    name: fail2ban
    state: restarted
  listen: selinux_module_nextcloud

- name: Restart postfix
  service:
    name: postfix
    state: restarted
  listen: restart_postfix

- name: Restart cyrus-imapd
  service:
    name: cyrus-imapd
    state: restarted
  listen: restart_cyrus_imapd

- name: Restart opendkim
  service:
    name: opendkim
    state: restarted
  listen: restart_opendkim
