# handlers file for nextcloud
- name: Restart postfix
  service:
    name: postfix
    state: restarted

- name: Restart cyrus-imapd
  service:
    name: cyrus-imapd
    state: restarted

- name: Restart httpd
  service:
    name: httpd
    state: restarted
  listen: restart_httpd
