- name: "autoconfig : Install Packages"
  package:
    name:
      - httpd
      - python3-flask
      - mod_auth_gssapi
      - mod_ssl
      - mod_session
      - python3-mod_wsgi
      - python3-ldap3
      - python3-configargparse
      - python3-toml
    state: latest

- name: "autoconfig : Create app folder"
  file:
    path: /var/www/autoconfig
    state: directory

- name: "autoconfig : Install apache config"
  template:
    src: autoconfig.conf
    dest: "/etc/httpd/conf.d/autoconfig.{{ ansible_domain }}.conf"
  notify: restart_httpd

- name: "autoconfig : Install webapp"
  copy:
    src: autoconfig
    dest: /var/www
  notify: restart_httpd

- name: "autoconfig : Install autoconfig.ini"
  template:
    src: autoconfig.ini
    dest: /var/www/autoconfig
  notify: restart_httpd

