- name: "postfix : Configure postfix"
  command: "postconf -e '{{ item.key }} = {{ item.value | join(', ') if item.value is not string else item.value }}'"
  with_dict: "{{ postfix_main_cfg_opts }}"
  changed_when: false

- name: "postfix : Enable submission service"
  command:
    cmd: >
        postconf -Me submission/inet='
        submission inet n - n - - smtpd -v -o
        {{
            postfix_master_cfg_opts.submission_inet.keys()
                | zip(postfix_master_cfg_opts.submission_inet.values())
                | map('join', '=')
                | join(' -o ')
        }}
        '
  changed_when: false

- name: "postfix : Create service smtp/{{ ansible_fqdn }}"
  ipaservice:
    name: "smtp/{{ ansible_fqdn }}"
  environment: "{{ env_ipa_on_host }}"

- name: "postfix : Create service alias smtp/{{ mailserver_fqdn }}"
  vars:
    ansible_python_interpreter: "{{ is_realmproxy | ternary('/usr/bin/python3.9', '/usr/bin/python3') }}"
  ipaservice:
    ipaadmin_password: "{{ ipaadmin_password | default(omit) }}"
    name: "smtp/{{ ansible_fqdn }}"
    principal: "smtp/{{ mailserver_fqdn }}"
  delegate_to: "{{ (ipaadmin_password is not defined) | ternary('127.0.0.1', omit) }}"
  become: no
  environment: "{{ env_ipa_on_server }}"
  when: mailserver_fqdn != ansible_fqdn

- name: "postfix : Get keytab for smtp"
  block:
    - name: "postfix : Get kerberos credentials"
      command: kinit -k
      changed_when: false

    - name: "postfix : Get keytab"
      command:
        cmd: "ipa-getkeytab -p smtp/{{ ansible_fqdn }} -k /etc/postfix/krb5.keytab"
        creates: /etc/postfix/krb5.keytab
  always:
    - name: Destroy credential cache
      command: kdestroy
      changed_when: false

- name: "postfix : Change owner of postfix keytab"
  file:
    path: /etc/postfix/krb5.keytab
    owner: postfix

- name: "postfix : Install virtual_ldap"
  template:
    src: virtual_ldap
    dest: /etc/postfix

- name: "postfix : Map virtual_ldap"
  command:
    cmd: postmap /etc/postfix/virtual_ldap

- name: "postfix : Configure saslauthd"
  copy:
    src: smtpd.conf
    dest: /etc/sasl2

- name: "postfix : Create folder for extra selinux modules"
  file:
    path: /var/local/selinux-modules
    state: directory

- name: "postfix : copy postfix-extra.te"
  copy:
    src: postfix-extra.te
    dest: /var/local/selinux-modules
  notify: selinux_module_postfix_extra
