- name: "postfix : Configure postfix"
  command: "postconf -e '{{ item.key }} = {{ item.value | join(', ') if item.value is not string else item.value }}'"
  loop: "{{ main_cfg_opts | dict2items }}"
  changed_when: false

- name: "postfix : Enable submission service"
  command:
    cmd: >
        postconf -Me submission/inet="
        submission inet n - n - - smtpd -v -o
        {{
            master_cfg_opts.submission_inet.keys()
                | zip(master_cfg_opts.submission_inet.values())
                | map('join', '=')
                | join(' -o ')
        }}
        "
  changed_when: false

- name: "postfix : Create service smtp/{{ ansible_fqdn }}"
  ipa_service:
    name: "smtp/{{ ansible_fqdn }}"
    ipa_host: "{{ ipa_server }}"
  environment:
    KRB5_CLIENT_KTNAME: /etc/krb5.keytab
    http_proxy: ""
    https_proxy: ""

- name: "postfix : Get keytab for smtp"
  block:
    - name: "postfix : Get kerberos credentials"
      command: kinit -k
      changed_when: false

    - name: "postfix : Get keytab"
      command:
        cmd: "ipa-getkeytab -p smtp/{{ ansible_fqdn }} -k /etc/postfix/krb5.keytab"
        creates: /etc/postfix/krb5.keytab
  always:
    - name: Destroy credential cache
      command: kdestroy
      changed_when: false

- name: "postfix : Change owner of postfix keytab"
  file:
    path: /etc/postfix/krb5.keytab
    owner: postfix

- name: "postfix : Install virtual_ldap"
  template:
    src: virtual_ldap
    dest: /etc/postfix

- name: "postfix : Map virtual_ldap"
  command:
    cmd: postmap /etc/postfix/virtual_ldap

- name: "postfix : Configure saslauthd"
  copy:
    src: smtpd.conf
    dest: /etc/sasl2

- name: Create folder for extra selinux modules
  file:
    path: /var/local/selinux-modules
    state: directory

- name: "postfix : copy postfix-extra.te"
  copy:
    src: postfix-extra.te
    dest: /var/local/selinux-modules
  notify: selinux_module_postfix_extra
